spring:
  application:
    name: ms-rutaexpress-bff

rutaexpress:
  shipments-url: ${SHIPMENTS_URL:http://localhost:8081}
  catalog-url: ${CATALOG_URL:http://localhost:8082}
  notify-url: ${NOTIFY_URL:http://localhost:8083}
  report-url: ${REPORT_URL:http://localhost:8084}
  audit-url: ${AUDIT_URL:http://localhost:8085}

server:
  port: 8080
